package com.example.legal.document.template.publication;

public enum TemplatePublicationErrorCode {
    TEMPLATE_PUBLICATION_INVALID,
    TEMPLATE_MARKER_MAPPING_INVALID,
    TEMPLATE_FIELD_SOURCE_INVALID,
    TEMPLATE_NORMALIZATION_FAILED,
    TEMPLATE_STORAGE_FAILED,
    TEMPLATE_PERSISTENCE_FAILED,
    TEMPLATE_NOT_FOUND,
    TEMPLATE_VERSION_NOT_FOUND
}
