package com.example.legal.document.generation;

public enum GenerationErrorCode {
    GENERATION_REQUEST_INVALID,
    GENERATION_CASE_NOT_FOUND,
    GENERATION_TEMPLATE_VERSION_NOT_FOUND,
    GENERATION_VALUE_STALE,
    GENERATION_IDEMPOTENCY_CONFLICT,
    GENERATION_TEMPLATE_INTEGRITY_FAILED,
    GENERATION_RENDERING_FAILED,
    GENERATION_STORAGE_FAILED,
    GENERATION_PERSISTENCE_FAILED
}
